export const interiors = [
    { id: 1, name: "· UI REDESIGN" },
    { id: 2, name: "· UI REDESIGN" },
    { id: 3, name: "· 프로젝트 제목" },
    { id: 4, name: "· 구찌 오스테리아 웹 사이트 리디자인" },
    { id: 5, name: "· 맥도날드 앱 리디자인" },
    { id: 6, name: "· 팀 프로젝트" },
    { id: 7, name: "Lunar Horizon Lounge" },
    { id: 8, name: "· UI REDESIGN" },
    { id: 9, name: "Lunar Horizon Lounge" },
    { id: 10, name: "Lunar Horizon Lounge" },
    { id: 11, name: "Lunar Horizon Lounge" },
    { id: 12, name: "· UI/UX REDESIGN" },
    { id: 13, name: "· UI/UX REDESIGN" },
    { id: 14, name: "· UI/UX REDESIGN" },
    { id: 15, name: "Lunar Horizon Lounge" },
    { id: 16, name: "· WEB REDESIGN" },
    { id: 17, name: "Lunar Horizon Lounge" },
    { id: 18, name: "· UI/UX REDESIGN" },
    { id: 19, name: "Lunar Horizon Lounge" },
    { id: 20, name: "· UI/UX REDESIGN" },
    { id: 21, name: "· UI/UX REDESIGN" },
    { id: 22, name: "Lunar Horizon Lounge" },
    { id: 23, name: "· UI/UX REDESIGN" },
    { id: 24, name: "Lunar Horizon Lounge" },
    { id: 25, name: "Lunar Horizon Lounge" },
    { id: 26, name: "Lunar Horizon Lounge" },
    { id: 27, name: "Lunar Horizon Lounge" },
    { id: 28, name: "Lunar Horizon Lounge" },
    { id: 29, name: "Lunar Horizon Lounge" },
    { id: 30, name: "Lunar Horizon Lounge" },
    { id: 31, name: "Lunar Horizon Lounge" },
    { id: 32, name: "Lunar Horizon Lounge" },
    { id: 33, name: "Lunar Horizon Lounge" },
    { id: 34, name: "Lunar Horizon Lounge" },
    { id: 35, name: "Lunar Horizon Lounge" },
    { id: 36, name: "Lunar Horizon Lounge" },
    { id: 37, name: "Lunar Horizon Lounge" },
    { id: 38, name: "Lunar Horizon Lounge" },
    { id: 39, name: "Lunar Horizon Lounge" },
    { id: 40, name: "Lunar Horizon Lounge" },
];
